### ISSUE TITLE
[bug] sinabs.layers.UnflattenTime will raise error with torch 1.8.1

### ISSUE THREAD

**Issue by Allan-Yoriichi** [synsense/sinabs#37]
### Description
It seems the `nn.Unflatten` doesn't support `-1` in the `unflattened_size` arg. 

The code below will meet an error with `torch 1.8.1`,  but works fine with `torch 1.9.0`

```python
import torch
import torch.nn as nn
input = torch.randn(2, 50)
lyr = nn.Unflatten(dim=1, unflattened_size=(5, -1))
out = lyr(input)
```

```
Traceback (most recent call last):
  File "/home/allan/.local/share/JetBrains/PyCharm2021.1/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/allan/.local/share/JetBrains/PyCharm2021.1/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/allan/PycharmProjects/snn_classifier_trainer/sinabs_snn_trainer/dradt1.py", line 8, in <module>
    out = lyr(input)
  File "/home/allan/PycharmProjects/snn_classifier_trainer/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/allan/PycharmProjects/snn_classifier_trainer/venv/lib/python3.6/site-packages/torch/nn/modules/flatten.py", line 131, in forward
    return input.unflatten(self.dim, self.unflattened_size)
  File "/home/allan/PycharmProjects/snn_classifier_trainer/venv/lib/python3.6/site-packages/torch/tensor.py", line 840, in unflatten
    return super(Tensor, self).unflatten(dim, sizes, names)
RuntimeError: unflatten: Provided sizes [5, -1] don't multiply up to the size of dim 1 (50) in the input tensor
python-BaseException

```

Maybe we should consider to update the torch requriements of sinabs to `>=1.9.0`

**Comment by biphasic** [comment]
Hey, thanks for reporting this! I fixed this in https://github.com/synsense/sinabs/commit/dfa25b0e60925fa592aaf2f804fbd71df406467b
the test pipeline is currently running but I tested locally with Pytorch 1.8.2
Please reopen if this is still an issue
